### ISSUE TITLE
No Projects Listed With Stage Definitions

### ISSUE THREAD

**Issue by dylanvalade** [18F/dashboard#258] opened 2015-10-01 00:58 UTC
This page states that it should [list the projects currently in each stage](https://18f.gsa.gov/dashboard/stages/#alpha) but none are displayed. The projects are visible [on the dashboard](https://18f.gsa.gov/dashboard/).

**Comment by DavidEBest** [comment] 2015-10-02 18:33
Thanks! This is actually a dupe of #252.

**Closed as completed** 2015-10-05 10:34 UTC
Labels: duplicate
